### ISSUE TITLE
[SIDELINE] Better checking for bad filter chain steps

### ISSUE THREAD

**Issue by stanlemon** [salesforce/storm-dynamic-spout#21]
`
java.lang.NullPointerException at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) at com.salesforce.storm.spout.sideline.filter.FilterChain.addStep(FilterChain.java:49) at com.salesforce.storm.spout.sideline.handler.SidelineSpoutHandler.onSpoutOpen(SidelineSpoutHandler.java:186) at com.salesforce.storm.spout.dynamic.DynamicSpout.open(DynamicSpout.java:186) at org.apache.storm.daemon.executor$fn_4962$fn4977.invoke(executor.clj:602) at org.apache.storm.util$async_loop$fn_557.invoke(util.clj:482) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745)
`

**Comment by stanlemon** [comment]
Looks like the sideline request might have deserialized wrong, which is odd.  So the problem isn't in the filter chain (thought I'm going add some preconditions to these methods to get more clear messages), but probably further up stream.  It might take a couple of rounds to get this one fully sorted.

**Comment by Crim** [comment]
Is it because the class path changed between versions?

**Comment by stanlemon** [comment]
Ah I bet that’s it! Good catch. Anyhow, I’m going to add some better handling so that’s clear all the way down.

**Comment by stanlemon** [comment]
Resolved in #37
