### ISSUE TITLE
[SIDELINE] Monitor and manage sideline spouts in the SpoutCoordinator

### ISSUE THREAD

**Issue by stanlemon** [salesforce/storm-dynamic-spout#27]
Specifically we need to make sure we always have a firehose, when it's not there we restart it.  Additionally we should check the sideline requests and use our existing resume logic to pick them back up.

**Comment by Crim** [comment]
It may be better to figure out how to have SpoutMonitor restart failed spout instances itself.  

Or we could push it down to the lifecycle handler.  On VirtualSpout abnormal termination/error -> call a hook method?

**Comment by stanlemon** [comment]
Is the monitor always going to know enough to restart them? That’s the part I’m concerned about. The identifiers are the only thing the monitor pays attention to today. Part of me thinks we should just provide spout handlers a clean interface for watching and tracking their spouts. I’m on the fence about this right now.
