### ISSUE TITLE
Trim Whitespace from Outputfields

### ISSUE THREAD

**Issue by danielsd** [salesforce/storm-dynamic-spout#33]
I think it would improve config readability if whitespace was trimmed from the output fields list so elements can spaced out in config files. Currently whitespace is used as part of the tuple fieldname. That said I'm not too familiar with yaml conventions so if whitespace is typically excluded from list values then perhaps it's better left alone.

https://github.com/salesforce/storm-dynamic-spout/blob/26e0643fb24ee7eeffbee2dd6041e3f819081b44/src/main/java/com/salesforce/storm/spout/dynamic/DynamicSpout.java#L239

**Comment by stanlemon** [comment]
Resolved in #35, note the preferred strategy will be to move to a list.

I will push a snapshot to maven central, should be there in a little bit.
