### ISSUE TITLE
[SIDELINE] Trigger reference implementation

### ISSUE THREAD

**Issue by stanlemon** [salesforce/storm-dynamic-spout#46]
Create a reference implementation of `SidelineTrigger` using Zookeeper watches (it's our preferred state machine at the moment).

**Comment by stanlemon** [comment]
@Crim as for a namespace for this, how does com.salesforce.storm.spout.sideline.trigger.example seem? Or should we do something else? Example makes sense, but I'm also afraid it might discourage people from using it out of the box, which is what I'm hoping they'll do.

**Comment by Crim** [comment]
@stanlemon To remove the dependency on kafka consumer from Sideline, I think we should do one of the following in SidelineSpoutHandler::loadSidelines():

- Remove `final String topic = (String) getSpoutConfig().get(KafkaConsumerConfig.KAFKA_TOPIC);` and replace with its own configuration value.

or

- Store the topic/namespace on the sideline request, and load it from there.

thoughts?

**Comment by stanlemon** [comment]
@Crim WIP over on #72 for that item.  Because the reference implementation is done I am going to go ahead and close this issue now.
