### ISSUE TITLE
Upgrade Storm Dependency to 1.1.1

### ISSUE THREAD

**Issue by Crim** [salesforce/storm-dynamic-spout#5]
Upgrade Storm Dependency to 1.1.1.   

This dependency is scoped at provided, and Storm 1.1.x <--> Storm 1.0.x appear to be compatible, so we should be able to continue supporting both versions.

**Comment by stanlemon** [comment]
@Crim do we want to bump the library to 0.9 when we do this? We might want to use milestones and aggregate some 0.9 changes together.

**Comment by Crim** [comment]
Sounds like a plan
