### ISSUE TITLE
Inconsistent default config values

### ISSUE THREAD

**Issue by danielsd** [salesforce/storm-dynamic-spout#84]
There is a minor inconsistency in that some config values are defaulted in SpoutConfig while others are in the retry manager. In some cases values are defaulted in both which seems redundant and the values even differ in some cases.

See `RETRY_MANAGER_INITIAL_DELAY_MS`
https://github.com/salesforce/storm-dynamic-spout/blob/master/src/main/java/com/salesforce/storm/spout/dynamic/config/SpoutConfig.java#L481
https://github.com/salesforce/storm-dynamic-spout/blob/master/src/main/java/com/salesforce/storm/spout/dynamic/retry/DefaultRetryManager.java#L58

**Comment by stanlemon** [comment]
I believe these are all in `SpoutConfig` now:
https://github.com/salesforce/storm-dynamic-spout/blob/b7a71a35c812e1272cdfe9d4b42c31592dcbf42c/src/main/java/com/salesforce/storm/spout/dynamic/config/SpoutConfig.java#L188-L271

If you see any other inconsistencies, please open a new issue, thanks!
